name: Package
on:
  push:
    branches:
      - main
jobs:
  package:
    name: Package easycharts for PyPI
    runs-on: ubuntu-latest
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Packaging dependencies
        run: |
          pip install wheel twine

      - name: Package & Test PyPI Installation
        run: |
          export NEXTVERSION=$(pip -qqq download easycharts && ls easycharts*.whl | sed 's/-/" "/g' | awk '{print "(" $2 ")"}' |  python nextbuild.py)
          sed -i 's/NEXTVERSION/'$NEXTVERSION'/g' setup.py
          python setup.py bdist_wheel
          export PYQL_PACKAGE=$(pwd)/dist/easycharts-$NEXTVERSION-py3-none-any.whl
          pip install $(echo -n $PYQL_PACKAGE)

      - name: Upload to PyPi
        env: # Or as an environment variable
          PYPI: ${{ secrets.PYPI }}
        run: |
          export NEXTVERSION=0.1 
          export PYQL_PACKAGE=$(pwd)/dist/easycharts-$NEXTVERSION-py3-none-any.whl
          python -m twine upload $(pwd)/dist/easycharts-$NEXTVERSION-py3-none-any.whl -u codemation -p $PYPI